import type { Metadata } from "next";
import { Newsreader, Inter } from "next/font/google";
import "./globals.css";

const newsreader = Newsreader({
  variable: "--font-wiki-serif",
  subsets: ["latin"],
  style: ["normal", "italic"],
});

const inter = Inter({
  variable: "--font-wiki-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alt-Wiki — The Alternate Encyclopedia",
  description: "Explore pixel-perfect alternate history and alternate reality Wikipedia articles generated by AI.",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${newsreader.variable} ${inter.variable}`}>
      <body className="bg-[#ffffff] text-[#202122] antialiased selection:bg-[#cce2ff] selection:text-[#000000]">
        {children}
      </body>
    </html>
  );
}
